wiki/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'

urlpatterns = [
    path("", views.index, name="index"),
    path('entry/<str:title>/', views.entry, name='entry'),
    path('random/', views.random_page, name='random_page'),
    path('new/', views.new_entry, name='new_entry'),
    path('entry/<str:title>/edit/', views.edit_entry, name='edit_entry'),
    path('search/', views.search, name='search'),
]

wiki/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/wiki/encyclopedia/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'Search Encyclopedia'}))

class NewEntryForm(forms.Form):
    title = forms.CharField(label="Title", max_length=100)
    content = forms.CharField(widget=forms.Textarea, label="Content")


class EditEntryForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea, label="Contenu Markdown")

wiki/wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
import random
import markdown2
from django.http import HttpResponseRedirect
from .forms import NewEntryForm
from .forms import EditEntryForm
from .forms import SearchForm
from . import util




def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, title):
    markdown_content = util.get_entry(title)

    if not markdown_content:
        return render(request, "encyclopedia/error.html", {
            "message": "La page demandée n'a pas été trouvée."
        })

    html_content = markdown2.markdown(markdown_content)

    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "content": html_content
    })


def search(request):
    query = request.GET.get('q')

    if not query:
        return redirect('encyclopedia:index')

    query = query.lower()
    entries = util.list_entries()

    matching_entries = [entry for entry in entries if query in entry.lower()]

    if len(matching_entries) == 1:
        return redirect('encyclopedia:entry', title=matching_entries[0])
    elif matching_entries:
        return render(request, "encyclopedia/search_results.html", {
            "entries": matching_entries
        })
    else:
        return render(request, "encyclopedia/search_results.html", {
            "entries": [],
            "message": "Aucun résultat trouvé pour votre recherche."
        })


def random_page(request):
    entries = util.list_entries()
    random_entry = random.choice(entries)

    return HttpResponseRedirect(reverse('encyclopedia:entry', args=[random_entry]))

def new_entry(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            if util.get_entry(title):
                context = {
                    "form": form,
                    "error_message": "This entry already exists!"
                }
                return render(request, "encyclopedia/new_entry.html", context)
            else:
                util.save_entry(title, content)
                return HttpResponseRedirect(reverse("encyclopedia:entry", args=[title]))
    else:
        return render(request, "encyclopedia/new_entry.html", {"form": NewEntryForm()})

def edit_entry(request, title):
    entry_content = util.get_entry(title)
    if request.method == "POST":
        form = EditEntryForm(request.POST)
        if form.is_valid():
            new_content = form.cleaned_data["content"]
            util.save_entry(title, new_content)
            return HttpResponseRedirect(reverse("encyclopedia:entry", args=[title]))
    else:
        form = EditEntryForm(initial={'content': entry_content})
    return render(request, "encyclopedia/edit_entry.html", {
        "title": title,
        "form": form
    })

wiki/wiki/encyclopedia/templates/encyclopedia/edit_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Modifier {{ title }}
{% endblock %}

{% block body %}
    <form action="{% url 'encyclopedia:edit_entry' title %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enregistrer les modifications">
    </form>
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {{ content|safe }}
    <a href="{% url 'encyclopedia:edit_entry' title %}">Modifier cette entrée</a>
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Erreur
{% endblock %}

{% block body %}
    <h2>Erreur</h2>
    <p>{{ message }}</p>
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                  <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                  <input type="submit" value="Search">
              </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_entry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/wiki/encyclopedia/templates/encyclopedia/new_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Entry
{% endblock %}

{% block body %}
    <h2>Create a New Entry</h2>
    <form action="{% url 'encyclopedia:new_entry' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Search Results
{% endblock %}

{% block body %}
<h2>Search Results</h2>

{% if entries %}
<ul>
    {% for entry in entries %}
    <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>{{ message }}</p>
{% endif %}

{% endblock %}